### ISSUE TITLE
注册

### ISSUE THREAD

**Issue by SeanChense** [UESTC-BBS/uestc-bbs#1]
> 或者用 WebView 显示注册网页；或者自己写一个服务器端 API。

WebView 显示注册页面很普遍，微软家的登录注册几乎都是走 WebView

**Comment by fangjue** [comment]
但是如果要良好的用户体验（注册成功就已经登录客户端），需要截获注册时输入的用户名和密码再用 API 登录一遍，实现起来也不一定很方便，而且 Android 和 iOS 两个版本都要分别实现一次。如果用 API 要方便一点。或者考虑修改一下现有的注册 API？

**Comment by SeanChense** [comment]
我不赞同。
1.印象中几乎很多主流的产品都是先注册再登录，没有采取截取用户的输入来自动登录。
2.Over-optimization make things worse.

**Comment by fangjue** [comment]
手机我用得少。但是河畔网页版，或者常用的其他网页版服务，一般不都是注册完以后已经处于已登录状态（如果需要邮件验证，点击验证链接后通常会最终跳转到登录后的页面）。注册完以后，再让用户重新输入一遍用户名和密码，我并不觉得有什么好处。

**Comment by SeanChense** [comment]
刚刚试了下知乎的注册流程，是带着 token 自动登录的。
那如果能改下现有的注册 API 返回 accessToken 拿着去登录就福。

如果是截取 WebView 的输入信息，我担心 iOS 的安全机制不允许我这么做。

**Comment by fangjue** [comment]
应该是这样的。目前河畔客户端的 API 注册后（注册成成电新人）也会返回 token。

截取 WebView 输入的密码很不优雅，还是考虑修改注册 API，或者增加实名关联 API 这两种方式。
