### ISSUE TITLE
命名、代码规范

### ISSUE THREAD

**Issue by fangjue** [UESTC-BBS/uestc-bbs#2]
例如：文件夹名称统一用 CamelCase，readme.md 统一用小写吗？

**Comment by SeanChense** [comment]
iOS 这边基本是 CamelCase，类名首字母大写 FooClass，变量首字母小写 fooClass

readme.md 是我随手写的，大小需要有规范吗？

**Comment by fangjue** [comment]
Anrdoid 这边 @fatekiller 你来决定，我看了几个 Android 示例似乎是包名（以及相关的文件夹）小写，类名大写。

我随手写的确是 README.md，所以需要讨论一下确定到底使用哪一个。我看你都用了小写，那我也改成小写吧。

PS. 这个显然不属于 enhancement。

**Comment by SeanChense** [comment]
GitHub 不能自己加 Label 真是不福。

**Comment by fangjue** [comment]
可以的：https://github.com/fangjue/uestc-bbs/labels

**Comment by SeanChense** [comment]
天噜 原来是这样。
但是本页没有入口 :-1: (
